# netlify.toml at repo root
[build]
base = "client"                 # run the build inside /client
command = "npm ci && npm run build"
publish = "dist"                # with base set, this is relative to /client

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--no-fund --no-audit"
NODE_OPTIONS = "--max_old_space_size=4096"

# SPA routing (react-router)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
