services:
  - type: web
    name: sms-backend
    env: node
    rootDir: "server"
    buildCommand: "npm ci"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
